version: '3.2'

services:
  mysql:
    image: 'mysql:5.7.21'
    container_name: 'mymysql'
    ports:
      - '33006:3306'
    #volumes:
    #  - '~/mnt/mysql/:/var/lib/mysql/'
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=stc
    command: mysqld --lower_case_table_names=1 --skip-ssl
#  redis:
#    image: 'redis:latest'
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - '6379:6379'
